### ISSUE TITLE
Orionjs TinyMce

### ISSUE THREAD

**Issue by rwatts3** [rwatts3/orionjs-contrib#6]
## Build Orionjs TinyMce

This issue is for the initial build of Orionjs TinyMce. 

**TODO**
- [ ] Independently load TinyMce without dependancies . 
- [ ] Create Orionjs attribute for TinyMce
- [ ] Create Orionjs filesystem support. 
- [ ] Write Tests. 
- [ ] Write Documentation
